# Generated by Django 5.1.4 on 2026-10-04 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('single_match', 'Single Match Pass'), ('supporter_bundle', 'Supporter Bundle'), ('season_pass', 'Season Access Pass'), ('playoff_pass', 'Playoff Match Pass'), ('finale_pass', 'Finale Celebration Pass')], db_index=True, max_length=20)),
                ('division', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South')], default='', max_length=10)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apparel_size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=4)),
                ('fulfillment_method', models.CharField(blank=True, choices=[('pickup', 'Pickup at venue'), ('ship', 'Ship')], default='', max_length=10)),
                ('product_name', models.CharField(max_length=500)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('checked_in', 'Checked In')], db_index=True, default='pending', max_length=12)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_checked_in', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['division', 'week_number', 'tier', 'status'], name='ticket_capacity_idx'), models.Index(fields=['tier', 'status'], name='ticket_tier_status_idx')],
            },
        ),
    ]
