# Generated by Django 5.1.4 on 2026-10-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ticket_capacity_buckets',
            },
        ),
    ]
