# Generated by Django 5.1.4 on 2026-05-20 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waiver_version', models.CharField(db_index=True, default='1.0', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('medical_conditions', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_rel', models.CharField(max_length=50, verbose_name='Emergency contact relationship')),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('clauses_initialed', models.JSONField(default=dict)),
                ('printed_name', models.CharField(max_length=100)),
                ('signature_image', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='waiver_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waiver_signatures',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['waiver_version', 'signed_at'], name='waiver_version_signed_idx')],
            },
        ),
    ]
