# Generated by Django 5.1.4 on 2026-04-19 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='captained_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active', 'name'], name='teams_active_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('max_players__gt', 0), ('max_players__lte', 30)), name='teams_max_players_range'),
        ),
    ]
