# Generated by Django 5.1.4 on 2026-05-06 04:57

import apps.teams.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('invite_type', models.CharField(choices=[('direct', 'Direct'), ('link', 'Link')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(default=apps.teams.models._default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_memberships',
                'ordering': ['-joined_at', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='teams_max_players_range',
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('official', 'Official')], db_index=True, default='forming', max_length=10),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status', 'is_active'], name='teams_status_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('max_players__gte', 8), ('max_players__lte', 11)), name='teams_max_players_range'),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='teams.teaminvite'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teaminvite',
            index=models.Index(fields=['team', 'status'], name='teaminvite_team_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvite',
            index=models.Index(fields=['invited_user', 'status'], name='teaminvite_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.UniqueConstraint(condition=models.Q(('invite_type', 'direct'), ('status', 'pending')), fields=('team', 'invited_user'), name='teaminvite_unique_pending_direct'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='membership_team_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'status'], name='membership_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='membership_unique_user_team'),
        ),
    ]
